name: Build and Deploy

env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically set by GitHub
  USE_GITHUB_DATA: "true"
  MEDIUM_USERNAME: "jabtech" # Change this if needed

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change to 'master' if your default branch is master
  schedule:
    - cron: "0 12 * * 1" # Weekly on Monday at 12:00 UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 22.x # Recommended Node version for your npm

      - name: Update npm 
        run: npm install -g npm@latest

      - name: Install Dependencies & Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
