name: Build and Deploy

on:
  workflow_dispatch:      # Manual trigger
  push:
    branches:
      - main             # Trigger on push to main
  schedule:
    - cron: "0 12 * * 1" # Optional: scheduled deployment every Monday at 12:00 UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Step 3: Install npm dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build React app
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}   # OR use token if you prefer
          # If you want to use GITHUB_TOKEN instead of SSH key:
          # token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
